### ISSUE TITLE
Which Turbo C Compiler?

### ISSUE THREAD

**Issue by haglebu** [climatex/8FORMAT#2]
I tried to compile with Borland Turbo-C 2.01 but I have no success.

**Comment by climatex** [comment]
And I thought that using version 3 was ancient enough :) Although, that is a C++ compiler, so some quirks were tolerated even when compiled as C code - e.g. single-line comments beginning with //, or asm directives with curly braces

Should be okay now, even with v2.01. Consult the build batch and adjust the TC/TCBIN variables accordingly.

**Comment by haglebu** [comment]
I compiled with TC 2.01; everything is fine!

**Comment by climatex** [comment]
Na dann viel Spass :)
